export interface MaterialPreset {
  namaMaterial: string;
  spesifikasi: string;
  satuan: string;
  tipe: 'MDU' | 'NON_MDU';
  defaultVolume?: number;
  kodePrefix?: string;
}

export const MDU_PRESETS: MaterialPreset[] = [
  {
    namaMaterial: 'Trafo Distribusi 20kV 400 kVA',
    spesifikasi: 'SPLN D3.002-1, 20kV/400V, Dyn5, Hermetically Sealed',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-TRF',
  },
  {
    namaMaterial: 'Trafo Distribusi 20kV 250 kVA',
    spesifikasi: 'SPLN D3.002-1, 20kV/400V, Dyn5, Minyak Mineral',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-TRF',
  },
  {
    namaMaterial: 'Trafo Distribusi 20kV 630 kVA',
    spesifikasi: 'SPLN D3.002-1, 20kV/400V, Dyn5, Trafindo / Bambang Djaja',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-TRF',
  },
  {
    namaMaterial: 'Kabel SKTM XLPE 20kV N2XSEBY 3x300 mm²',
    spesifikasi: 'SPLN 43-5, Cu/XLPE/CWS/PVC/DSTA/PVC 12/20 (24) kV',
    satuan: 'meter',
    tipe: 'MDU',
    defaultVolume: 350,
    kodePrefix: 'MDU-KBL',
  },
  {
    namaMaterial: 'Kabel SKTM XLPE 20kV N2XSEBY 3x150 mm²',
    spesifikasi: 'SPLN 43-5, Cu/XLPE/CWS/PVC/DSTA/PVC 12/20 (24) kV',
    satuan: 'meter',
    tipe: 'MDU',
    defaultVolume: 250,
    kodePrefix: 'MDU-KBL',
  },
  {
    namaMaterial: 'Kabel Udara Twisted LVTC 3x70 + 1x50 mm²',
    spesifikasi: 'SPLN 42-10, Al/XLPE Tegangan Rendah 0.6/1kV',
    satuan: 'meter',
    tipe: 'MDU',
    defaultVolume: 500,
    kodePrefix: 'MDU-LVTC',
  },
  {
    namaMaterial: 'Tiang Beton Pratekan 12 Meter 350 daN',
    spesifikasi: 'SPLN D3.019-1, Bulat Berongga, WIKA Beton',
    satuan: 'batang',
    tipe: 'MDU',
    defaultVolume: 6,
    kodePrefix: 'MDU-TNG',
  },
  {
    namaMaterial: 'Tiang Beton Pratekan 11 Meter 350 daN',
    spesifikasi: 'SPLN D3.019-1, Bulat Berongga, Standar PLN',
    satuan: 'batang',
    tipe: 'MDU',
    defaultVolume: 4,
    kodePrefix: 'MDU-TNG',
  },
  {
    namaMaterial: 'Tiang Beton Pratekan 9 Meter 200 daN',
    spesifikasi: 'SPLN D3.019-1, Untuk Jaringan TR 380V',
    satuan: 'batang',
    tipe: 'MDU',
    defaultVolume: 8,
    kodePrefix: 'MDU-TNG',
  },
  {
    namaMaterial: 'Kubikel 20kV Incoming 630A 20kA',
    spesifikasi: 'SPLN S3.001-1, LBS + Earthing Switch Motorized',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-KBK',
  },
  {
    namaMaterial: 'Kubikel 20kV Outgoing Proteksi CB 630A',
    spesifikasi: 'SPLN S3.001-1, Vacuum Circuit Breaker + Relay Sepam',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-KBK',
  },
  {
    namaMaterial: 'PHB-TR 4 Jurusan 400A Komplit',
    spesifikasi: 'SPLN 118-3-1, Busbar Tembaga 630A + Fuse Base NH-2',
    satuan: 'set',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-PHB',
  },
  {
    namaMaterial: 'Fused Cut Out (FCO) 24kV 100A',
    spesifikasi: 'SPLN 52-3, Keramik/Polimer + Fuse Link 20A/40A',
    satuan: 'set',
    tipe: 'MDU',
    defaultVolume: 3,
    kodePrefix: 'MDU-FCO',
  },
  {
    namaMaterial: 'Lightning Arrester (LA) 24kV 10kA Logam Oksida',
    spesifikasi: 'SPLN 52-4, Gapless Metal Oxide Polymer Disconnector',
    satuan: 'set',
    tipe: 'MDU',
    defaultVolume: 3,
    kodePrefix: 'MDU-LA',
  },
  {
    namaMaterial: 'LBS Motorized 20kV Outdoor Pole Mounted',
    spesifikasi: 'SPLN S3.002, SF6 Insulated + RTU SCADA Interface',
    satuan: 'unit',
    tipe: 'MDU',
    defaultVolume: 1,
    kodePrefix: 'MDU-LBS',
  }
];

export const NON_MDU_PRESETS: MaterialPreset[] = [
  {
    namaMaterial: 'Jointing Kit Kabel SKTM 20kV 3x300 mm²',
    spesifikasi: 'Raychem Heatshrinkable / 3M Coldshrink 24kV',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 2,
    kodePrefix: 'NON-JNT',
  },
  {
    namaMaterial: 'Jointing Kit Kabel SKTM 20kV 3x150 mm²',
    spesifikasi: 'Raychem Heatshrinkable / 3M Coldshrink 24kV',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 2,
    kodePrefix: 'NON-JNT',
  },
  {
    namaMaterial: 'Termination Indoor Kabel SKTM 20kV 3x300 mm²',
    spesifikasi: 'Raychem EPKT-24C / 3M QT-III Indoor 24kV',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 2,
    kodePrefix: 'NON-TRM',
  },
  {
    namaMaterial: 'Termination Outdoor Kabel SKTM 20kV 3x150 mm²',
    spesifikasi: 'Raychem EPKT-24C / 3M QT-III Outdoor Silikon',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 2,
    kodePrefix: 'NON-TRM',
  },
  {
    namaMaterial: 'Guy Wire / Trestang Tiang 12m Komplit',
    spesifikasi: 'Kawat Baja Galvanis 35mm² + Span Wartel + Anker Blok',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 4,
    kodePrefix: 'NON-TRT',
  },
  {
    namaMaterial: 'Tap Connector CCO 70 - 150 mm²',
    spesifikasi: 'Bahan Tembaga Tinned C-Wedge Type',
    satuan: 'buah',
    tipe: 'NON_MDU',
    defaultVolume: 24,
    kodePrefix: 'NON-CCO',
  },
  {
    namaMaterial: 'Sepatu Kabel Bimetal AL-CU 150 mm²',
    spesifikasi: 'Heavy Duty Friction Welded Bimetallic Lug',
    satuan: 'buah',
    tipe: 'NON_MDU',
    defaultVolume: 12,
    kodePrefix: 'NON-SPT',
  },
  {
    namaMaterial: 'Sepatu Kabel Tembaga Cu 300 mm² M12',
    spesifikasi: 'Tinned Copper Heavy Duty Cable Lug SPLN',
    satuan: 'buah',
    tipe: 'NON_MDU',
    defaultVolume: 12,
    kodePrefix: 'NON-SPT',
  },
  {
    namaMaterial: 'Grounding Rod Tembaga Murni 5/8" x 3 Meter',
    spesifikasi: 'Pure Solid Copper Rod + Klem Pengikat Grounding',
    satuan: 'batang',
    tipe: 'NON_MDU',
    defaultVolume: 4,
    kodePrefix: 'NON-GND',
  },
  {
    namaMaterial: 'Kabel BC (Bare Copper) Tembaga Telanjang 50 mm²',
    spesifikasi: 'SPLN 41-1, Soft Drawn Bare Copper Conductor',
    satuan: 'meter',
    tipe: 'NON_MDU',
    defaultVolume: 60,
    kodePrefix: 'NON-BC',
  },
  {
    namaMaterial: 'Mur Baut Hotdip Galvanis (HDG) M16 x 50 mm',
    spesifikasi: 'Grade 8.8 Anti Karat Outdoor + Ring Plat & Per',
    satuan: 'buah',
    tipe: 'NON_MDU',
    defaultVolume: 50,
    kodePrefix: 'NON-BAUT',
  },
  {
    namaMaterial: 'Cross Arm UNP 80 x 45 x 2000 mm (Bastek TM)',
    spesifikasi: 'Baja Profil UNP Hot Dip Galvanized Tebal 5mm',
    satuan: 'batang',
    tipe: 'NON_MDU',
    defaultVolume: 6,
    kodePrefix: 'NON-ARM',
  },
  {
    namaMaterial: 'Pipa Pelindung Subduct HDPE OD 160 mm',
    spesifikasi: 'SDR 11 PN 16 High Density Polyethylene Roll',
    satuan: 'meter',
    tipe: 'NON_MDU',
    defaultVolume: 80,
    kodePrefix: 'NON-PPA',
  },
  {
    namaMaterial: 'Isolator Tumpu Line Post 20kV Polymer',
    spesifikasi: 'SPLN D3.018-2, Creepage Distance 600mm + Stud Pin',
    satuan: 'buah',
    tipe: 'NON_MDU',
    defaultVolume: 18,
    kodePrefix: 'NON-ISL',
  },
  {
    namaMaterial: 'Plat Tanda Bahaya Kilat 20kV & No. Tiang',
    spesifikasi: 'Aluminium Plat Cat Reflektif Standar K3 PLN',
    satuan: 'set',
    tipe: 'NON_MDU',
    defaultVolume: 6,
    kodePrefix: 'NON-K3',
  }
];
